# $NetBSD: Makefile,v 1.112 2009/01/16 14:40:31 wiz Exp $

DISTNAME=	p5-Reaction-depends-0.03
CATEGORIES=	local
MASTER_SITES=	# empty

MAINTAINER=	abs@absd.org
HOMEPAGE=	http://dev.catalystframework.org/wiki/reaction
COMMENT=	Meta package for Reaction depends

META_PACKAGE=	yes

# T365 - Reaction

DEPENDS+= p5-ExtUtils-MakeMaker>=6.11:../../devel/p5-ExtUtils-MakeMaker
DEPENDS+= p5-Catalyst-Runtime>=5.7002:../../www/p5-Catalyst-Runtime
DEPENDS+= p5-Catalyst-Component-InstancePerContext>=0:../../www/p5-Catalyst-Component-InstancePerContext
DEPENDS+= p5-Catalyst-Plugin-ConfigLoader>=0.19:../../www/p5-Catalyst-Plugin-ConfigLoader
DEPENDS+= p5-Catalyst-Plugin-Static-Simple>=0:../../www/p5-Catalyst-Plugin-Static-Simple
DEPENDS+= p5-Catalyst-Plugin-I18N>=0.08:../../www/p5-Catalyst-Plugin-I18N
DEPENDS+= p5-Catalyst-Model-DBIC-Schema>=0:../../databases/p5-Catalyst-Model-DBIC-Schema
DEPENDS+= p5-Catalyst-View-TT>=0.23:../../www/p5-Catalyst-View-TT
DEPENDS+= p5-Config-General>=0:../../devel/p5-Config-General
DEPENDS+= p5-Test-Class>=0.31:../../devel/p5-Test-Class
DEPENDS+= p5-Test-Memory-Cycle>=1.04:../../devel/p5-Test-Memory-Cycle
DEPENDS+= p5-DBIx-Class>=0.07001:../../databases/p5-DBIx-Class
DEPENDS+= p5-DBIx-Class-IntrospectableM2M>=0.001000:../../databases/p5-DBIx-Class-IntrospectableM2M
DEPENDS+= p5-SQL-Translator>=0.08:../../databases/p5-SQL-Translator
DEPENDS+= p5-Moose>=0.58:../../devel/p5-Moose
DEPENDS+= p5-aliased>=0.22:../../devel/p5-aliased
DEPENDS+= p5-DateTime>=0.4501:../../time/p5-DateTime
DEPENDS+= p5-DateTime-Event-Recurrence>=0.16:../../time/p5-DateTime-Event-Recurrence
DEPENDS+= p5-DateTime-Format-MySQL>=0:../../time/p5-DateTime-Format-MySQL
DEPENDS+= p5-Time-modules>=0:../../time/p5-Time-modules
DEPENDS+= p5-Email-Valid>=0:../../mail/p5-Email-Valid
DEPENDS+= p5-Crypt-Eksblowfish>=0.005:../../security/p5-Crypt-Eksblowfish
DEPENDS+= p5-Email-Send>=0:../../mail/p5-Email-Send
DEPENDS+= p5-Email-MIME>=1.861:../../mail/p5-Email-MIME
DEPENDS+= p5-Email-MIME-Creator>=1.454:../../mail/p5-Email-MIME-Creator
DEPENDS+= p5-Text-CSV_XS>=0:../../textproc/p5-Text-CSV_XS
DEPENDS+= p5-Devel-Declare>=0.003004:../../devel/p5-Devel-Declare
DEPENDS+= p5-MooseX-Types>=0.04:../../devel/p5-MooseX-Types
DEPENDS+= p5-MooseX-Types-Common:../../devel/p5-MooseX-Types-Common
DEPENDS+= p5-MooseX-Types-DateTime:../../time/p5-MooseX-Types-DateTime
DEPENDS+= p5-Scalar-List-Utils>=0:../../devel/p5-Scalar-List-Utils
DEPENDS+= p5-File-ShareDir>=1.00:../../devel/p5-File-ShareDir
DEPENDS+= p5-namespace-clean>=0.08:../../devel/p5-namespace-clean
DEPENDS+= p5-Catalyst-Component-ACCEPT_CONTEXT>=0:../../www/p5-Catalyst-Component-ACCEPT_CONTEXT

.include "../../mk/bsd.pkg.mk"
