# $NetBSD: Makefile,v 1.112 2009/01/16 14:40:31 wiz Exp $

DISTNAME=	natbsync-depends-0.01
CATEGORIES=	local
MASTER_SITES=	# empty

MAINTAINER=	abs@absd.org
HOMEPAGE=	http://www.absd.org/
COMMENT=	Meta package for NATBsync server dependencies
META_PACKAGE=	yes

DEPENDS+= py26-django>0:../../www/py-django
DEPENDS+= py26-psycopg2>0:../../databases/py-psycopg2

.include "../../mk/bsd.pkg.mk"
