#!/bin/sh -e
# $Id: nbbuild,v 1.19 2008/11/18 15:01:18 abs Exp $

# Simple script to build NetBSD plus (locally defined) useful kernels
# Cannot use release until problem overflowing tiny boot floppy resolved

TARGET=distribution # sets
VERSION=$(uname -r)

VERSION=$(case "$VERSION" in
    *.99.*) echo current ;;
    *) echo $VERSION | sed 's/\..*//' ;;
esac)

while getopts Cht:uv f; do
  case $f in
	C) VERSION=current	;;
	h) opt_h=1		;;
	t) VERSION="$OPTARG"	;;
	u) opt_u=-u		;;
	v) opt_v=1		;;
    esac
done
shift `expr $OPTIND - 1`

if [ -n "$opt_h" ] ; then
    cat <<END
Usage: nbbuild [opts] [arch ...]
[opts]	-C     Build 'current' directory
	-h     This help
	-t tag Build 'tag' directory
	-u     MKUPDATE=yes
	-v     Verbose (display build log to stdout)
END
    exit
fi

if [ -d /opt/netbsd ] ; then
    FILEDIR=/opt/netbsd
else
    FILEDIR=/home/netbsd
fi
NBHOME=$(cd $FILEDIR ; pwd)
export BSDSRCDIR=$NBHOME/$VERSION

build()
    {
    MACHINE=$1

    case $MACHINE in
	vax)
	    FORMAT=tgz
	    ;;
	*)
	    if [ $VERSION = current ] || [ $VERSION -gt 5 ] ; then
	        FORMAT=txz
	    else
	        FORMAT=tbz
	    fi
	    ;;
    esac

    cd $BSDSRCDIR

    LASTMOD=$(stat -t %F -f %Sm CVS/Entries)
    OBJBASE=/var/obj/nbbuild-$VERSION-$MACHINE
    ARCHDIR=$NBHOME/arch/$VERSION-$MACHINE-$LASTMOD
    LOG=$OBJBASE/nbbuild.log

    if [ -z "$opt_u" ]; then
	rm -rf $OBJBASE
    fi
    mkdir -p $OBJBASE

    BUILD="./build.sh -m $MACHINE -U $opt_u \
	    -D $OBJBASE/destdir \
	    -O $OBJBASE/objdir \
	    -T $OBJBASE/tooldir \
	    -R $OBJBASE/releasedir \
	    release"
    echo $BUILD
    if [ -n "$opt_v" ] ; then
	COMPLETE=$OBJBASE/ok
	touch $COMPLETE
	($BUILD 2>&1 && touch $COMPLETE) | tee $OBJBASE/nbbuild.log
	[ ! -f $COMPLETE ] && exit
    elif ! $BUILD > $OBJBASE/nbbuild.log 2>&1 ; then
	tail -60 $LOG
	exit 1
    fi

    cd $OBJBASE/releasedir/$MACHINE/binary/sets
    mkdir -p $ARCHDIR
    echo -n "Recompress to $ARCHDIR:"
    for f in *.tgz ; do
	out=$(echo $f|sed "s/\.tgz$/.$FORMAT/")
	echo -n " $out"
	case $FORMAT in
	    txz)
		zcat $f | xz -9    > $ARCHDIR/$out
		;;
	    tbz)
		zcat $f | bzip2 -9 > $ARCHDIR/$out
		;;
	    tgz)
		cp $f $ARCHDIR/$out
		;;
	esac
    done
    echo

    if [ -z "$opt_u" ]; then
	rm -rf $OBJBASE
    fi
    }

if [ -z "$1" ] ; then
    build $(uname -m)
else
    for m ; do
	build $m
    done
fi
