# $NetBSD$

DISTNAME=	print-depends-1.00
CATEGORIES=	local
MASTER_SITES=	# empty

MAINTAINER=	abs@absd.org
HOMEPAGE=	http://www.absd.org/
COMMENT=	Meta package for printing tools

META_PACKAGE=	yes

DEPENDS+= cups>0:../../print/cups
DEPENDS+= brlaser>0:../../print/brlaser

.include "../../mk/bsd.pkg.mk"
