#!/bin/sh -e
cd /pkgsrc/editors/yed 
distfile="$(make show-var VARNAME=DISTFILES)"
if [ -z "$distfile" ] ; then
    echo "Unable to extract distfile for /pkgsrc/editors/yed"
    exit 1
fi
cd /pkgsrc/distfiles
if [ -f "$distfile" ] ; then
    echo "Rename $distfile to $distfile.old"
    mv "$distfile" "$distfile.old"
fi
