#!/bin/sh
#
# $NetBSD: INSTALL,v 1.4 2002/02/05 05:14:46 jlam Exp $

UPDATE_CONFIG=@PREFIX@/bin/update-config

case ${STAGE} in
POST-INSTALL)

    if [ -f /etc/rc.local ] && ! grep -q $UPDATE_CONFIG /etc/rc.local ; then
	echo "Update /etc/rc.local"
	echo "[ -x $UPDATE_CONFIG ] && $UPDATE_CONFIG" >> /etc/rc.local
    fi

    LOCAL_CSHRC=@PREFIX@/share/local/csh.cshrc
    if [ ! -f /etc/csh.cshrc ] || ! grep -q "source.*${LOCAL_CSHRC}" \
							/etc/csh.cshrc ; then
	echo "Update /etc/csh.cshrc"
	echo "if ( -f ${LOCAL_CSHRC} ) source ${LOCAL_CSHRC}" >> /etc/csh.cshrc
    fi

    LOCAL_PROFILE=@PREFIX@/share/local/profile
    if [ ! -f /etc/profile ] || ! grep -q "${LOCAL_PROFILE}" /etc/profile ; then
	echo "Update /etc/profile"
	cat >> /etc/profile <<END
# Added by pkgsrc/localtools
ENV=/usr/pkg/share/local/profile
[ -n "$BASH_VERSION" ] && . /usr/pkg/share/local/profile
END
    fi

    if [ ! -f /etc/zshenv ] || ! grep -q "${LOCAL_PROFILE}" /etc/zshenv ; then
	echo "Update /etc/zshenv"
	cat >> /etc/zshenv <<END
# Added by pkgsrc/localtools
[ -f /usr/pkg/share/local/profile ] && . /usr/pkg/share/local/profile
END
    fi

    for f in /root/.cshrc /root/.login /root/.tcshrc ; do
	if [ -f $f ] ; then
	    echo "Removing $f"
	    rm -f $f
	fi
    done

    ;;
esac
