# $NetBSD: Makefile,v 1.112 2009/01/16 14:40:31 wiz Exp $

DISTNAME=	3b-retail-depends-0.01
CATEGORIES=	local
MASTER_SITES=	# empty

MAINTAINER=	abs@absd.org
HOMEPAGE=	http://www.3b.net/
COMMENT=	Meta package for 3b retail/scraper depends

META_PACKAGE=	yes

DEPENDS+= ap2-fcgid>0:../../www/ap2-fcgid
DEPENDS+= ms-ttf>0:../../fonts/ms-ttf
DEPENDS+= p5-Class-DBI>0:../../databases/p5-Class-DBI
DEPENDS+= p5-Class-Inspector>0:../../devel/p5-Class-Inspector
DEPENDS+= p5-Class-MethodMaker>0:../../devel/p5-Class-MethodMaker
DEPENDS+= p5-DBD-postgresql>0:../../databases/p5-DBD-postgresql
DEPENDS+= p5-DBIx-ContextualFetch>0:../../databases/p5-DBIx-ContextualFetch
DEPENDS+= p5-Data-Dump>0:../../devel/p5-Data-Dump
DEPENDS+= p5-Data-FormValidator>0:../../textproc/p5-Data-FormValidator
DEPENDS+= p5-DateTime-Format-ISO8601>0:../../time/p5-DateTime-Format-ISO8601
DEPENDS+= p5-DateTime>0:../../time/p5-DateTime
DEPENDS+= p5-Digest-SHA1>0:../../security/p5-Digest-SHA1
DEPENDS+= p5-Email-Date>0:../../mail/p5-Email-Date
DEPENDS+= p5-Email-Valid>0:../../mail/p5-Email-Valid
DEPENDS+= p5-File-Modified>0:../../devel/p5-File-Modified
DEPENDS+= p5-File-Slurp>0:../../devel/p5-File-Slurp
DEPENDS+= p5-File-Type>0:../../devel/p5-File-Type
DEPENDS+= p5-Font-TTFMetrics>0:../../fonts/p5-Font-TTFMetrics
DEPENDS+= p5-HTML-Mason>0:../../www/p5-HTML-Mason
DEPENDS+= p5-HTML-Strip>0:../../www/p5-HTML-Strip
DEPENDS+= p5-IP-Country>0:../../net/p5-IP-Country
DEPENDS+= p5-Image-Size>0:../../graphics/p5-Image-Size
DEPENDS+= p5-JSON-Any>0:../../converters/p5-JSON-Any
DEPENDS+= p5-List-MoreUtils>0:../../devel/p5-List-MoreUtils
DEPENDS+= p5-Module-Build>0:../../devel/p5-Module-Build
DEPENDS+= p5-Module-Refresh>0:../../devel/p5-Module-Refresh
DEPENDS+= p5-Net-eBay>0:../../net/p5-Net-eBay
DEPENDS+= p5-Path-Class>0:../../devel/p5-Path-Class
DEPENDS+= p5-Perl6-Slurp>0:../../devel/p5-Perl6-Slurp
DEPENDS+= p5-PerlMagick>0:../../graphics/p5-PerlMagick
DEPENDS+= p5-RRDTool-OO>0:../../graphics/p5-RRDTool-OO
DEPENDS+= p5-Term-ProgressBar>0:../../devel/p5-Term-ProgressBar
DEPENDS+= p5-Term-Size>0:../../devel/p5-Term-Size
DEPENDS+= p5-Test-LongString>0:../../devel/p5-Test-LongString
DEPENDS+= p5-Tree-Simple>0:../../devel/p5-Tree-Simple
DEPENDS+= p5-WWW-Mechanize>0:../../www/p5-WWW-Mechanize
DEPENDS+= p5-XML-LibXML>0:../../textproc/p5-XML-LibXML
DEPENDS+= p5-XML-Parser>0:../../textproc/p5-XML-Parser
DEPENDS+= p5-XML-Simple>0:../../textproc/p5-XML-Simple
DEPENDS+= p5-YAML>0:../../textproc/p5-YAML
DEPENDS+= p5-version>0:../../devel/p5-version
DEPENDS+= postgresql83>0:../../databases/postgresql83
DEPENDS+= rrdtool>0:../../databases/rrdtool
DEPENDS+= vera-ttf>0:../../fonts/vera-ttf

.include "../../mk/bsd.pkg.mk"
