DISTNAME=	kde-subset-1.03
CATEGORIES=	local
MASTER_SITES=	# empty

MAINTAINER=	abs@absd.org
HOMEPAGE=	https://www.kde.org/
COMMENT=	Useful subset of KDE

META_PACKAGE=	yes

DEPENDS+= okular>0:../../print/okular
DEPENDS+= gwenview>0:../../graphics/gwenview

DEPENDS+= kde-baseapps4>0:../../x11/kde-baseapps4
DEPENDS+= kde-runtime4>0:../../x11/kde-runtime4
DEPENDS+= kde-workspace4>0:../../x11/kde-workspace4
DEPENDS+= kdeartwork4>0:../../misc/kdeartwork4

DEPENDS+= ark>0:../../archivers/ark
DEPENDS+= dolphin-plugins>0:../../devel/dolphin-plugins
DEPENDS+= kcolorchooser>0:../../graphics/kcolorchooser

DEPENDS+= kdenlive>0:../../multimedia/kdenlive

.include "../../mk/bsd.pkg.mk"
